import { 
  Home, 
  Zap, 
  CreditCard, 
  Phone, 
  Menu as MenuIcon, 
  Key, 
  Info,
  ShieldCheck,
  Droplets,
  Trash2,
  Bot,
  ArrowUpDown,
  Calculator,
  Map as MapIcon,
  Megaphone,
  Coins,
  Flame,
  FireExtinguisher,
  Clock,
  Smartphone,
  FileText,
  Download
} from 'lucide-react';
import { MenuItem, Notice } from './types';

export const APP_NAME = "Holan Tower";

export const ADMIN_PASSWORD = import.meta.env.VITE_ADMIN_PASSWORD || '123';

export const NOTICES: Notice[] = [
  { id: 1, text: "মাসিক সার্ভিস চার্জ প্রতি মাসের ৭ তারিখের মধ্যে পরিশোধ করুন", icon: Megaphone, date: "2024-05-20" },
  { id: 2, text: "মাসিক সার্ভিস চার্জের টাকা ভবনের রক্ষণাবেক্ষণ কাজে ব্যয় হয়", icon: Coins, date: "2024-05-21" },
  { id: 3, text: "পানি ও বিদ্যুৎ অপচয় রোধ করুন", icon: Droplets, date: "2024-05-22" },
  { id: 4, text: "বাইরে যাওয়ার আগে গ্যাসের চুলা ও বৈদ্যুতিক লাইন বন্ধ রাখুন", icon: Flame, date: "2024-05-22" },
  { id: 5, text: "ফায়ার এক্সটিংগুইশার এর অবস্থান জানুন", icon: FireExtinguisher, date: "2024-05-22" },
  { id: 6, text: "নির্ধারিত স্থানে ময়লা ফেলুন", icon: Trash2, date: "2024-05-22" },
  { id: 7, text: "ভবনের নিরাপত্তা নিশ্চিত করুন", icon: ShieldCheck, date: "2024-05-22" },
  { id: 8, text: "লিফট ব্যবহারে সতর্ক থাকুন", icon: ArrowUpDown, date: "2024-05-22" }
];

export const MENU_NOTICE_TEXT = "হলান টাওয়ারে আপনাকে স্বাগতম। আমাদের ভবনের সকল গুরুত্বপূর্ণ তথ্য ও দৈনন্দিন সেবাগুলি এখনে দ্রুত পেয়ে যাবেন। এখানে জরুরী নোটিশ, ইউটিলিটি ও সার্ভিস চার্জ, ডেসকো রিচার্জ, যোগাযোগ ও জরুরী হেল্পলাইন, ম্যাপ ও রুট নির্দেশনা, প্রিপেইড মিটার নাম্বার, লিফট ব্যবহারের নিয়ম, গ্যালারি এবং বাসাভাড়ার তথ্য একসাথে সহজে খুঁজে পাবেন। এটি হলান টাওয়ারের বাসিন্দাদের জন্য একটি দ্রুত, সহজ ও নির্ভরযোগ্য ডিজিটাল সার্ভিস কেন্দ্র।";

export const DESCO_NOTICE_TEXT = "ডেসকো প্রিপেইড মিটারে রিচার্জ করতে হলে অবশ্যই অ্যাকাউন্ট নাম্বার প্রয়োজন হবে। নিচে উল্লেখিত সকল ইউনিটের একাউন্ট নাম্বার আপডেট করে দেওয়া হলো। সতর্কতার সাথে রিচার্জ করতে হবে, ১ মিটারের রিচার্জ যেন অন্য মিটারে না হয়।";

export const SERVICE_CHARGE_NOTICE_TEXT = "আগামী মাসের সার্ভিস চার্জ অনুগ্রহ করে প্রতি মাসের ৭ তারিখের মধ্যে পরিশোধ করার জন্য বিশেষভাবে অনুরোধ করা যাচ্ছে। নির্ধারিত সময়ের মধ্যে সার্ভিস চার্জ পরিশোধ না করলে ভবনের রক্ষণাবেক্ষণ, নিরাপত্তা, পরিচ্ছন্নতা ও অন্যান্য সেবামূলক কার্যক্রম ব্যাহত হতে পারে। সবার সহযোগিতায় আমাদের ভবনকে পরিষ্কার, নিরাপদ ও সুশৃঙ্খল রাখি। -- ধন্যবাদান্তে, ব্যবস্থাপনা কমিটি";

export const EMERGENCY_NOTICE_TEXT = "সম্মানিত ফ্ল্যাট মালিক ও বাসিন্দাবৃন্দ, বিল্ডিং সংক্রান্ত যেকোনো সমস্যা যেমন — লিফট, বিদ্যুৎ, পানি, গ্যাস, নিরাপত্তা বা অন্যান্য জরুরি বিষয় দেখা দিলে অনুগ্রহ করে নোটিশ বোর্ড/অ্যাপে প্রদত্ত জরুরি যোগাযোগ নম্বরে দ্রুত যোগাযোগ করুন। দ্রুত যোগাযোগ করলে সমস্যা সমাধান সহজ ও দ্রুত করা সম্ভব হবে। সবার সহযোগিতায় আমাদের ভবনকে নিরাপদ ও সুশৃঙ্খল রাখি।";


export const MENU_ITEMS: MenuItem[] = [
  { 
    id: 'service', 
    label: 'সার্ভিস চার্জ', 
    icon: CreditCard, 
    view: 'SERVICE_CHARGE',
    color: 'bg-blue-500',
    description: 'মাসিক বিল ও পেমেন্ট',
    gradient: 'from-blue-500 to-cyan-500'
  },
  { 
    id: 'desco', 
    label: 'ডেসকো রিচার্জ', 
    icon: Zap, 
    view: 'DESCO',
    color: 'bg-yellow-500',
    description: 'প্রিপেইড মিটার তথ্য',
    gradient: 'from-amber-400 to-orange-500'
  },
  { 
    id: 'recharge_rules', 
    label: 'রিচার্জ করার নিয়ম', 
    icon: Smartphone, 
    view: 'RECHARGE_RULES',
    color: 'bg-orange-500',
    description: 'সহজ রিচার্জ নির্দেশিকা',
    gradient: 'from-orange-400 to-red-500'
  },
  { 
    id: 'accounts', 
    label: 'স্বচ্ছ হিসাব কেন্দ্র', 
    icon: Calculator, 
    view: 'ACCOUNTS',
    color: 'bg-indigo-500',
    description: 'বিল্ডিং এর আয়-ব্যয়',
    gradient: 'from-indigo-500 to-purple-600'
  },
  { 
    id: 'tolet', 
    label: 'বাসাভাড়া / টু-লেট', 
    icon: Key, 
    view: 'TO_LET',
    color: 'bg-emerald-500',
    description: 'ফ্ল্যাট খালি আছে',
    gradient: 'from-emerald-400 to-green-600'
  },
  { 
    id: 'emergency', 
    label: 'জরুরী নম্বর', 
    icon: ShieldCheck, 
    view: 'EMERGENCY',
    color: 'bg-red-600',
    description: 'পুলিশ, ফায়ার, অ্যাম্বুলেন্স',
    gradient: 'from-red-500 to-rose-700'
  },
  { 
    id: 'emergency_notice', 
    label: 'জরুরী নোটিশ', 
    icon: Megaphone, 
    view: 'EMERGENCY_NOTICE_DETAIL',
    color: 'bg-red-500',
    description: 'গুরুত্বপূর্ণ ঘোষণা',
    gradient: 'from-red-600 to-rose-500'
  },
  { 
    id: 'water', 
    label: 'পানির বিল', 
    icon: Droplets, 
    view: 'WATER_BILL',
    color: 'bg-cyan-500',
    description: 'ওয়াসা বিল তথ্য',
    gradient: 'from-cyan-400 to-blue-500'
  },
  { 
    id: 'map', 
    label: 'ম্যাপ ও বিভিন্ন রুট', 
    icon: MapIcon, 
    view: 'MAP_ROUTES',
    color: 'bg-teal-500',
    description: 'লোকেশন ও নির্দেশনা',
    gradient: 'from-teal-400 to-emerald-600'
  },
  { 
    id: 'prayer', 
    label: 'নামাজের সময়', 
    icon: Clock, 
    view: 'PRAYER_TIME',
    color: 'bg-indigo-500',
    description: 'আজকের নামাজের সময়সূচী',
    gradient: 'from-indigo-400 to-purple-600'
  },
  { 
    id: 'policy', 
    label: 'নীতিমালা অনুমোদন ও কার্যকর', 
    icon: FileText, 
    view: 'POLICY',
    color: 'bg-rose-500',
    description: 'নিয়মাবলী ও নির্দেশনা',
    gradient: 'from-rose-400 to-pink-600'
  },
  { 
    id: 'lift', 
    label: 'লিফট নির্দেশাবলি', 
    icon: ArrowUpDown,
    view: 'LIFT_INSTRUCTIONS',
    color: 'bg-slate-500',
    description: 'লিফট ব্যবহারের নিয়মাবলী',
    gradient: 'from-slate-400 to-gray-600'
  },
  { 
    id: 'download', 
    label: 'ডাউনলোড অ্যাপ', 
    icon: Download,
    view: 'DOWNLOAD_APP',
    color: 'bg-purple-500',
    description: 'অ্যাপটি ডাউনলোড করুন',
    gradient: 'from-purple-400 to-violet-600'
  },
  { 
    id: 'contact', 
    label: 'যোগাযোগ', 
    icon: Phone,
    view: 'CONTACT',
    color: 'bg-teal-500',
    description: 'জরুরী যোগাযোগ নম্বর',
    gradient: 'from-teal-400 to-emerald-600'
  }
];

export const FLAT_OWNERS = [
  { flat: '2A', name: 'MATIN', account: '41371285' },
  { flat: '2B', name: 'HANIF', account: '41371286' },
  { flat: '2C', name: 'MINA', account: '41371287' },
  { flat: '3A', name: 'JILLUR', account: '41371298' },
  { flat: '3B', name: 'KAIYUM', account: '41371308' },
  { flat: '3C', name: 'FARUK', account: '41371291' },
  { flat: '4A', name: 'SAIDUR', account: '41371310' },
  { flat: '4B', name: 'IBRAHIM', account: '41371303' },
  { flat: '4C', name: 'AYUB', account: '41371296' },
  { flat: '5A', name: 'MOJAMMEL', account: '41371302' },
  { flat: '5B', name: 'NESAR', account: '41371295' },
  { flat: '5C', name: 'JUWEL', account: '41371309' },
  { flat: '6A', name: 'NESAR', account: '41371299' },
  { flat: '6B', name: 'SHAHIN', account: '41371305' },
  { flat: '6C', name: 'SHAHIDULAH', account: '41371292' },
  { flat: '7A', name: 'AZAD', account: '41371294' },
  { flat: '7B', name: 'MOROL', account: '41371293' },
  { flat: '7C', name: 'NAZRUL', account: '41371284' },
  { flat: '8A', name: 'ATIQ', account: '41371306' },
  { flat: '8B', name: 'MOSTOFA', account: '41371304' },
  { flat: '8C', name: 'FIROZ', account: '41371301' },
  { flat: '9A', name: 'KAIYUM', account: '41371307' },
  { flat: '9B', name: 'AZHAR', account: '41371297' },
  { flat: '9C', name: 'SAYED', account: '41371300' },
  { flat: '10A', name: 'HAKIM', account: '41371288' },
  { flat: '10B', name: 'MOTIUR', account: '41371289' },
  { flat: '10C', name: 'ASHRAF', account: '41371290' },
  { flat: 'MAIN', name: 'NAZRUL', account: '41371283' }
];

export const TRANSLATIONS = {
  bn: {
    appName: 'হলান টাওয়ার',
    common: {
      serviceCenter: 'সেবা কেন্দ্র',
      allServices: 'সকল সেবা',
      viewAll: 'সব দেখুন',
      todayDate: 'আজকের তারিখ',
      seconds: 'সেকেন্ড',
      maintenanceDesk: 'মেইনটেন্যান্স ডেস্ক',
      settings: 'সেটিং',
      back: 'ফিরে যান',
      save: 'সেভ করুন',
      cancel: 'বাতিল',
      confirm: 'নিশ্চিত',
      loading: 'লোড হচ্ছে...',
      error: 'ত্রুটি',
      success: 'সফল হয়েছে',
      delete: 'মুছে ফেলুন',
      edit: 'এডিট',
      add: 'যোগ করুন',
      search: 'খুঁজুন...',
      noData: 'কোনো তথ্য পাওয়া যায়নি',
      viewDetails: 'বিস্তারিত দেখুন',
      hideDetails: 'বিস্তারিত লুকান',
      showDetails: 'বিস্তারিত দেখুন',
      yes: 'হ্যাঁ',
      no: 'না',
      ok: 'ঠিক আছে',
      retry: 'আবার চেষ্টা করুন',
      saveError: 'সেভ করতে সমস্যা হয়েছে: ',
      unknownError: 'একটি ত্রুটি ঘটেছে: ',
    },
    hollanTowerResident: 'হলান টাওয়ার বাসী',
    serviceCharge: 'সার্ভিস চার্জ',
    demo: 'ডেমো',
    adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড',
    editInfo: 'যেকোনো ইউনিটে ক্লিক করে পেমেন্ট স্ট্যাটাস পরিবর্তন করুন।',
    allUnitsCalc: 'সকল ইউনিট হিসাব',
    financialYear: 'অর্থবছর',
    total: 'সর্বমোট',
    status: 'অবস্থা',
    unit: 'ইউনিট',
    totalCollected: 'মোট জমা',
    totalDue: 'মোট বাকি',
    searchUnit: 'ইউনিট খুঁজুন (যেমন: 2A)',
    details: 'বিস্তারিত দেখতে ক্লিক করুন',
    all: 'সকল',
    flatType: 'ফ্ল্যাটের ধরন',
    paid: 'পরিশোধিত',
    due: 'বকেয়া',
    upcoming: 'আসন্ন',
    adminLogin: 'অ্যাডমিন লগইন',
    loginPrompt: 'ডেটা এডিট করতে পিন কোড দিন',
    loginBtn: 'লগইন করুন',
    totalAmount: 'মোট টাকা',
    occupancy: 'বসবাসের ধরন',
    occupied: 'বসবাসরত',
    vacant: 'খালি',
    monthDate: 'মাস ও তারিখ',
    amount: 'টাকা',
    saveFail: 'সেভ করতে ব্যর্থ হয়েছে',
    statusChangeFail: 'স্ট্যাটাস পরিবর্তন করতে ব্যর্থ হয়েছে',
    month: 'মাস',
    paymentStatus: 'পেমেন্ট স্ট্যাটাস',
    notice: 'নোটিশ',
    exitTitle: 'অ্যাপ বন্ধ করুন',
    exitMessage: 'আপনি কি নিশ্চিতভাবে অ্যাপটি বন্ধ করতে চান?',
    exitConfirm: 'হ্যাঁ, বন্ধ করুন',
    exitCancel: 'না',
    mobile: 'মোবাইল',
    note: 'নোট',
    date: 'তারিখ',
    year: 'বছর',
    balance: 'উদ্বৃত্ত',
    income: 'আয়',
    expense: 'ব্যয়',
    action: 'অ্যাকশন',
    admin: 'অ্যাডমিন',
    user: 'ইউজার',
    password: 'পাসওয়ার্ড',
    incorrectPassword: 'ভুল পাসওয়ার্ড',
    pin: 'পিন',
    incorrectPin: 'ভুল পিন কোড!',
    securityPin: 'নিরাপত্তা পিন',
    unlockEdit: 'এডিট মোড আনলক করুন',
    months: [
      'জানুয়ারি', 'ফেব্রুয়ারি', 'মার্চ', 'এপ্রিল', 'মে', 'জুন',
      'জুলাই', 'আগস্ট', 'সেপ্টেম্বর', 'অক্টোবর', 'নভেম্বর', 'ডিসেম্বর'
    ],
    menuItems: {
      service: { label: 'সার্ভিস চার্জ', desc: 'মাসিক বিল ও পেমেন্ট' },
      desco: { label: 'ডেসকো রিচার্জ', desc: 'প্রিপেইড মিটার তথ্য' },
      recharge_rules: { label: 'রিচার্জ করার নিয়ম', desc: 'সহজ রিচার্জ নির্দেশিকা' },
      accounts: { label: 'স্বচ্ছ হিসাব কেন্দ্র', desc: 'বিল্ডিং এর আয়-ব্যয়' },
      tolet: { label: 'বাসাভাড়া / টু-লেট', desc: 'ফ্ল্যাট খালি আছে' },
      emergency: { label: 'জরুরী নম্বর', desc: 'পুলিশ, ফায়ার, অ্যাম্বুলেন্স' },
      emergency_notice: { label: 'জরুরী নোটিশ', desc: 'গুরুত্বপূর্ণ ঘোষণা' },
      water: { label: 'পানির বিল', desc: 'ওয়াসা বিল তথ্য' },
      map: { label: 'ম্যাপ ও বিভিন্ন রুট', desc: 'লোকেশন ও নির্দেশনা' },
      prayer: { label: 'নামাজের সময়', desc: 'আজকের নামাজের সময়সূচী' },
      policy: { label: 'নীতিমালা অনুমোদন ও কার্যকর', desc: 'নিয়মাবলী ও নির্দেশনা' },
      lift: { label: 'লিফট নির্দেশাবলি', desc: 'লিফট ব্যবহারের নিয়মাবলী' },
      download: { label: 'ডাউনলোড অ্যাপ', desc: 'অ্যাপটি ডাউনলোড করুন' },
      contact: { label: 'যোগাযোগ', desc: 'জরুরী যোগাযোগ নম্বর' }
    },
    bottomNav: {
      service: 'সার্ভিস চার্জ',
      desco: 'ডেসকো',
      home: 'হোম',
      contact: 'যোগাযোগ',
      menu: 'মেনু'
    },
    greetings: {
      morning: 'শুভ সকাল',
      noon: 'শুভ দুপুর',
      afternoon: 'শুভ বিকেল',
      evening: 'শুভ সন্ধ্যা',
      night: 'শুভ রাত্রি'
    },
    location: 'হলান, দক্ষিণখান',
    designBy: 'ডিজাইন করেছেন এ.এইচ.এম রিফাত হাসান',
    notices: [
      "মাসিক সার্ভিস চার্জ প্রতি মাসের ৭ তারিখের মধ্যে পরিশোধ করুন",
      "মাসিক সার্ভিস চার্জের টাকা ভবনের রক্ষণাবেক্ষণ কাজে ব্যয় হয়",
      "পানি ও বিদ্যুৎ অপচয় রোধ করুন",
      "বাইরে যাওয়ার আগে গ্যাসের চুলা ও বৈদ্যুতিক লাইন বন্ধ রাখুন",
      "ফায়ার এক্সটিংগুইশার এর অবস্থান জানুন",
      "নির্ধারিত স্থানে ময়লা ফেলুন",
      "ভবনের নিরাপত্তা নিশ্চিত করুন",
      "লিফট ব্যবহারে সতর্ক থাকুন"
    ],
    menuNotice: "হলান টাওয়ারে আপনাকে স্বাগতম। আমাদের ভবনের সকল গুরুত্বপূর্ণ তথ্য ও দৈনন্দিন সেবাগুলি এখনে দ্রুত পেয়ে যাবেন। এখানে জরুরী নোটিশ, ইউটিলিটি ও সার্ভিস চার্জ, ডেসকো রিচার্জ, যোগাযোগ ও জরুরী হেল্পলাইন, ম্যাপ ও রুট নির্দেশনা, প্রিপেইড মিটার নাম্বার, লিফট ব্যবহারের নিয়ম, গ্যালারি এবং বাসাভাড়ার তথ্য একসাথে সহজে খুঁজে পাবেন। এটি হলান টাওয়ারের বাসিন্দাদের জন্য একটি দ্রুত, সহজ ও নির্ভরযোগ্য ডিজিটাল সার্ভিস কেন্দ্র।",
    descoNotice: "ডেসকো প্রিপেইড মিটারে রিচার্জ করতে হলে অবশ্যই অ্যাকাউন্ট নাম্বার প্রয়োজন হবে। নিচে উল্লেখিত সকল ইউনিটের একাউন্ট নাম্বার আপডেট করে দেওয়া হলো। সতর্কতার সাথে রিচার্জ করতে হবে, ১ মিটারের রিচার্জ যেন অন্য মিটারে না হয়।",
    serviceChargeNotice: "আগামী মাসের সার্ভিস চার্জ অনুগ্রহ করে প্রতি মাসের ৭ তারিখের মধ্যে পরিশোধ করার জন্য বিশেষভাবে অনুরোধ করা যাচ্ছে। নির্ধারিত সময়ের মধ্যে সার্ভিস চার্জ পরিশোধ না করলে ভবনের রক্ষণাবেক্ষণ, নিরাপত্তা, পরিচ্ছন্নতা ও অন্যান্য সেবামূলক কার্যক্রম ব্যাহত হতে পারে। সবার সহযোগিতায় আমাদের ভবনকে পরিষ্কার, নিরাপদ ও সুশৃঙ্খল রাখি। -- ধন্যবাদান্তে, ব্যবস্থাপনা কমিটি",
    emergencyNotice: "সম্মানিত ফ্ল্যাট মালিক ও বাসিন্দাবুরন্দ, বিল্ডিং সংক্রান্ত যেকোনো সমস্যা যেমন — লিফট, বিদ্যুৎ, পানি, গ্যাস, নিরাপত্তা বা অন্যান্য জরুরি বিষয় দেখা দিলে অনুগ্রহ করে নোটিশ বোর্ড/অ্যাপে প্রদত্ত জরুরি যোগাযোগ নম্বরে দ্রুত যোগাযোগ করুন। দ্রুত যোগাযোগ করলে সমস্যা সমাধান সহজ ও দ্রুত করা সম্ভব হবে। সবার সহযোগিতায় আমাদের ভবনকে নিরাপদ ও সুশৃঙ্খল রাখি।",
    accounts: {
      title: 'স্বচ্ছ হিসাব খাতা',
      subtitle: 'বাৎসরিক আর্থিক বিবরণী',
      currentBalance: 'বর্তমান উদ্বৃত্ত',
      totalIncome: 'মোট আয়',
      totalExpense: 'মোট ব্যয়',
      netSurplus: 'নিট উদ্বৃত্ত',
      incomeDetails: 'আয় বিবরণী',
      expenseDetails: 'ব্যয় বিবরণী',
      surplusFromLastMonth: 'আগের মাসের উদ্বৃত্ত',
      fixedExpenses: {
        electricity: 'বিদ্যুৎ বিল',
        water: 'পানি বিল',
        garbage: 'ময়লার বিল',
        caretaker: 'গার্ড/কেয়ারটেকার বেতন',
        nightGuard: 'নাইট গার্ড বিল',
      },
      otherIncome: 'অন্যান্য হতে আয়',
      otherExpense: 'অন্যান্য হতে ব্যয়',
      specialNote: 'বিশেষ নোট / মন্তব্য',
      upcoming: 'আসন্ন',
    },
    descoView: {
      title: 'DESCO স্মার্ট মিটার',
      accountNo: 'অ্যাকাউন্ট নম্বর',
      meterNo: 'মিটার নম্বর',
      checkBalance: 'ব্যালেন্স জানুন',
      recharge: 'রিচার্জ করুন',
      quickRecharge: 'দ্রুত রিচার্জ',
      paymentGuide: 'পেমেন্ট নির্দেশিকা',
      confirmRecharge: 'রিচার্জ নিশ্চিত করুন',
      loadingMeter: 'মিটার তথ্য লোড হচ্ছে',
      meterNotFound: 'মিটার তথ্য পাওয়া যায়নি',
      selectFlat: 'আপনার ফ্ল্যাট নং সিলেক্ট করুন',
      noFlatSelected: 'কোনো ফ্ল্যাট সিলেক্ট হয়নি',
      searchPlaceholder: 'সার্চ (যেমন 2A বা নাম)...',
      noResult: 'কোনো ফলাফল পাওয়া যায়নি',
      flatNumber: 'আপনার ফ্ল্যাট নম্বর',
      ownerName: 'মালিকপক্ষের নাম',
      accountNumber: 'ডেসকো অ্যাকাউন্ট নাম্বার',
      confirmTitle: 'নিশ্চিত করুন',
      confirmDesc: 'অ্যাকাউন্ট নম্বর কপি করতে নিচের বাটনে ক্লিক করুন',
      subtitle: 'প্রিপেইড মিটার তথ্য',
      infoBox: 'মিটার তথ্য',
      rulesBox: 'রিচার্জ নিয়ম',
      allFloors: 'সকল ফ্লোর',
      mainMeter: 'মেইন মিটার',
      notice: 'বিশেষ দ্রষ্টব্য:',
      account: 'অ্যাকাউন্ট',
      tapToCopy: 'কপি করতে ট্যাপ করুন',
      flat: 'ফ্ল্যাট',
      owner: 'মালিক',
      paymentNote: 'পেমেন্ট করার পর ট্রানজিশন আইডি সংরক্ষণ করুন।',
      payNow: 'এখনই পে করুন',
      copySuccess: 'অ্যাকাউন্ট নম্বর কপি করা হয়েছে!',
      copyFail: 'কপি ব্যর্থ',
      disclaimer: 'তথ্যগুলো শুধুমাত্র আপনার সহায়তার জন্য।',
      warning: 'সতর্কতা: ভুল অ্যাকাউন্টে রিচার্জ করলে কর্তৃপক্ষ দায়ী থাকবে না।',
      popupTitle: 'দ্রুত রিচার্জ পপআপ',
      popupText: 'আপনি কি এই অ্যাকাউন্টে রিচার্জ করতে চান?',
      popupNote: 'সতর্কতা: রিচার্জ করার আগে অ্যাকাউন্ট নম্বর মিলিয়ে নিন।',
      popupDetails: 'বিস্তারিত তথ্য',
      rechargeNow: 'রিচার্জ করুন',
      mobileBanking: 'মোবাইল ব্যাংকিং',
      floor: 'তলা',
    },
    emergencyView: {
      title: 'জরুরী সার্ভিস ও কন্ট্রাক্টর',
      newDepartment: 'নতুন ডিপার্টমেন্ট',
      addNumber: 'নতুন নম্বর যোগ করুন',
      editNumber: 'নম্বর এডিট করুন',
      name: 'নাম',
      role: 'ভূমিকা',
      mobileNumber: 'মোবাইল নম্বর',
      hasWhatsapp: 'WhatsApp আছে',
      departmentName: 'ডিপার্টমেন্টের নাম',
      createDepartment: 'তৈরি করুন',
      call: 'কল',
      copied: 'কপি হয়েছে',
      confirmDeleteNumber: 'আপনি কি নিশ্চিত যে আপনি এই নম্বরটি মুছে ফেলতে চান?',
      confirmDeleteDept: 'আপনি কি নিশ্চিত যে আপনি এই সম্পূর্ণ ডিপার্টমেন্টটি মুছে ফেলতে চান? এর অন্তর্গত সমস্ত নম্বর মুছে যাবে।',
    },
    serviceChargeView: {
      monthlyServiceCharge: 'মাসিক সার্ভিস চার্জ',
      dashboard: 'সার্ভিস চার্জ ড্যাশবোর্ড',
      allUnitsList: 'সকল ইউনিটের তালিকা',
      paymentHistory: 'পেমেন্ট হিস্ট্রি',
      dueList: 'বকেয়া তালিকা',
      parkingCharge: 'পার্কিং চার্জ',
      adminPanel: 'অ্যাডমিন প্যানেল',
      dataEntry: 'ডেটা এন্ট্রি',
      twelveMonthsInfo: '১২ মাসের তথ্য',
      unitAndDate: 'ইউনিট ও তারিখ',
      partial: 'আংশিক',
      paidStatus: 'পরিশোধ',
      dueStatus: 'বকেয়া',
      remaining: 'বাকি',
      grandTotal: 'মোট যোগফল',
      yearlySummary: 'বাৎসরিক সামারি',
      yearlyCalculation: 'এর হিসাব',
      totalCollectedYear: 'বছরে মোট আদায়',
      totalDueYear: 'বছরে মোট বকেয়া',
      highestDueMonth: 'সবচেয়ে বেশি বকেয়া',
      wasDueThisMonth: 'এই মাসে বকেয়া ছিল',
      totalBillable: 'বছরের মোট দাবি (Billable)',
      paymentUpdate: 'পেমেন্ট আপডেট',
      occupancyType: 'বসবাসের ধরন (এই মাসের জন্য)',
      parkingType: 'পার্কিং ধরন',
      motorcycle: 'মোটরসাইকেল',
      car: 'গাড়ি',
      ownershipType: 'মালিকানার ধরন',
      flatOwner: 'ফ্ল্যাট মালিক',
      tenant: 'ভাড়াটিয়া',
      external: 'বাহিরস্থ',
      paymentDate: 'পেমেন্ট তারিখ',
      on: 'অন আছে',
      off: 'অফ আছে',
      updateBtn: 'আপডেট করুন',
      agingReport: 'বকেয়া রিপোর্ট (Aging)',
      oneMonthDue: '১ মাসের বকেয়া',
      twoMonthsDue: '২ মাসের বকেয়া',
      threePlusMonthsDue: '৩+ মাসের বকেয়া',
      totalAccumulatedDue: 'মোট পুঞ্জীভূত বকেয়া',
      monthlyCharge: 'মাসিক চার্জ',
      allPaid: 'সব পরিশোধিত',
      totalDue: 'মোট বকেয়া',
      infoOfTwelveMonths: 'এর ১২ মাসের তথ্য',
      adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড',
      editInfo: 'তথ্য সম্পাদনা করুন',
      whatsappMessage: 'হোয়াটসঅ্যাপ মেসেজ',
      sendNotification: 'নোটিফিকেশন পাঠান',
      sendSms: 'এসএমএস পাঠান',
      sendSmsToAll: 'সকল ইউনিটে এসএমএস পাঠান',
      manageParkingUnits: 'পার্কিং ইউনিট পরিচালনা করুন',
      addCarOrParking: 'গাড়ি বা পার্কিং যোগ করুন',
      refreshData: 'ডেটা রিফ্রেশ করুন',
      selectTarget: 'টার্গেট নির্বাচন করুন',
      clearAll: 'সব মুছে ফেলুন',
      whatsappTitle: 'হোয়াটসঅ্যাপ মেসেজ',
      saveToSupabase: 'সুপাবেসে সেভ করুন',
      savedSuccessfully: 'সফলভাবে সেভ হয়েছে!',
      savedLocally: 'লোকালি সেভ হয়েছে!',
      back: 'ফিরে যান',
      whatsapp: 'হোয়াটসঅ্যাপ',
      sms: 'এসএমএস',
      pdf: 'পিডিএফ',
      download: 'ডাউনলোড',
      print: 'প্রিন্ট',
      share: 'শেয়ার',
      copy: 'কপি',
      link: 'লিঙ্ক',
      view: 'ভিউ',
      occupied: 'বসবাসরত',
      vacant: 'খালি',
      billNotGenerated: 'এই মাসের বিল এখনো তৈরি হয়নি',
      parkingChargeWithService: 'সার্ভিস চার্জ সহ পার্কিং চার্জ',
      viewTogether: 'এক সাথে দেখুন',
      onlyParkingCharge: 'শুধু পার্কিং চার্জ',
      viewSeparately: 'আলাদাভাবে দেখুন',
      summaryReport: 'সামারি রিপোর্ট',
      year: 'সাল',
      flatNumber: 'ফ্ল্যাট নম্বর',
      unknown: 'অজানা',
      totalDueAmount: 'মোট বকেয়া',
      unitDetailsInstruction: '। কোনো ইউনিট এর হিসাব দেখতে উপরের ইউনিট এ ক্লিক করুন। সকল ইউনিট এর হিসাব ডিটেইস এ দেওয়া আছে।',
      parkingChargePdf: 'পার্কিং চার্জ পিডিএফ ডাউনলোড',
      serviceChargePdf: 'সার্ভিস চার্জ পিডিএফ ডাউনলোড',
      reportOfUnit: 'ইউনিট {{unit}} এর {{year}} সালের রিপোর্ট',
      emergencyNotePlaceholder: 'এখানে জরুরী নোট লিখুন...',
      clickToAddNote: 'নোট যোগ করতে এখানে ক্লিক করুন...',
      noNote: 'কোনো নোট নেই',
      detailedYearlyAccount: 'এই ইউনিটের পুরো বছরের বিস্তারিত হিসাব দেখুন',
      paidList: 'পরিশোধিত তালিকা',
      unitCount: '{{unit}} সংখ্যা',
      remainingCount: 'বাকি আছে',
      monthStatPaid: 'এই মাসে {{total}} ইউনিটের মধ্যে {{paid}}টি পরিশোধ করেছে।',
      monthStatDue: 'এবং {{total}} ইউনিটের মধ্যে {{due}}টি বাকি আছে।',
      noUnitFound: 'কোনো ইউনিট পাওয়া যায়নি',
      upcoming: 'আসন্ন',
      clickMonthForPopup: 'মাসে ক্লিক করলে ডেটা এন্ট্রি জন্য পপআপ উইন্ডো আসবে',
      status: 'অবস্থা',
      unitLabel: 'ইউনিট:',
      monthLabel: 'মাস:',
      yearLabel: 'সাল',
      calculationOf: 'এর হিসাব',
      count: 'সংখ্যা',
      provideApiSenderMessage: 'অনুগ্রহ করে API Key, Sender ID এবং Message প্রদান করুন।',
      selectAtLeastOneUnit: 'অনুগ্রহ করে অন্তত একটি ইউনিট নির্বাচন করুন।',
      confirmSendSms: 'আপনি কি নিশ্চিত যে আপনি {{count}} টি ইউনিটে এসএমএস পাঠাতে চান?',
      receivedKeyword: 'পাওয়া গেছে',
      acceptedKeyword: 'গ্রহণ করা হয়েছে',
      successfullyKeyword: 'সফলভাবে',
      smsSendingCompleted: 'এসএমএস পাঠানো সম্পন্ন হয়েছে!\nসফল: {{success}}\nব্যর্থ: {{fail}}',
      problemSendingSms: 'এসএমএস পাঠাতে সমস্যা হয়েছে।',
      aiAssistant: 'এআই অ্যাসিস্ট্যান্ট',
      writeMessageHere: 'আপনার মেসেজ এখানে লিখুন...',
      units: 'ইউনিট সমূহ',
      deselectAll: 'সব বাতিল করুন',
      selectAll: 'সব নির্বাচন করুন',
      sent: 'পাঠানো হয়েছে',
      sending: 'পাঠানো হচ্ছে...',
      currentMonthMessage: 'চলতি মাসের বার্তা',
      dueMonthMessageOwner: 'বকেয়া মাসের বার্তা (মালিকপক্ষ)',
      dueSummary: 'বকেয়া সামারি',
      years2025And2026: '২০২৫ ও ২০২৬ সাল',
      totalDue2025: '২০২৫ মোট বকেয়া',
      totalDue2026: '২০২৬ মোট বকেয়া',
      grandTotalDue: 'সর্বমোট বকেয়া',
      unitWiseDueList: 'ইউনিট ভিত্তিক বকেয়া তালিকা',
      monthlySummary: 'মাসিক সামারি',
      viewDetailedYearlyAccount: 'পুরো বছরের বিস্তারিত হিসাব দেখুন',
      dueAccount2025And2026: '২০২৫ ও ২০২৬ সালের বকেয়া হিসাব',
      unitWiseSummary: 'ইউনিট ভিত্তিক সামারি',
      viewYearlyAccount: 'পুরো বছরের হিসাব দেখুন',
      viewDetails: 'বিস্তারিত দেখুন',
      backToServiceCharge: 'সার্ভিস চার্জে ফিরে যান',
      currentlyViewingParkingCharge: 'বর্তমানে পার্কিং চার্জ দেখছেন',
      viewMonthlyDetailedAccount: 'প্রতি মাসের বিস্তারিত হিসাব দেখুন',
      parkingUnits: 'পার্কিং ইউনিট সমূহ',
      amount: 'টাকা',
      noDateOrAmountNeeded: 'তারিখ বা টাকার পরিমাণ প্রয়োজন নেই',
      totalAmount: 'মোট টাকা',
      selectParkingUnits: 'পার্কিং ইউনিট নির্বাচন করুন',
      selectParkingUnitsDescription: 'যেসব ইউনিটের পার্কিং আছে সেগুলো নির্বাচন করুন',
      buildingUnits: 'বিল্ডিংয়ের ইউনিট',
      externalParking: 'বাহিরস্থ পার্কিং',
      ownerName: 'মালিকের নাম',
      add: 'যোগ করুন',
      cancel: 'বাতিল',
      saving: 'সংরক্ষণ করা হচ্ছে...',
      save: 'সংরক্ষণ করুন',
      smsSender: 'এসএমএস সেন্ডার',
      viaBulkSms: 'বাল্ক এসএমএস বিডি এর মাধ্যমে',
      apiKey: 'এপিআই কী (API Key)',
      apiKeyPlaceholder: 'আপনার API Key দিন',
      senderId: 'সেন্ডার আইডি (Sender ID)',
      senderIdPlaceholder: 'আপনার Sender ID দিন',
      selectMonth: 'মাস নির্বাচন করুন',
      selectTemplate: 'টেমপ্লেট নির্বাচন করুন',
      paymentRequestTemplate: 'পেমেন্ট রিকোয়েস্ট',
      paymentRequest: 'সম্মানিত বাসিন্দা (ইউনিট: {{unit}}), আপনার সার্ভিস চার্জ ({{amount}} টাকা) পরিশোধের জন্য অনুরোধ করা হলো। ধন্যবাদ।',
      sendToAllUnits: 'সকল ইউনিটে পাঠান',
      paymentReceivedTemplate: 'পেমেন্ট রিসিভড',
      paymentReceived: 'সম্মানিত বাসিন্দা (ইউনিট: {{unit}}), আপনার সার্ভিস চার্জ ({{amount}} টাকা) সফলভাবে গ্রহণ করা হয়েছে। ধন্যবাদ।',
      forIndividualUnits: 'নির্দিষ্ট ইউনিটের জন্য',
      dueReminderTemplate: 'বকেয়া রিমাইন্ডার',
      dueReminder: 'সম্মানিত বাসিন্দা (ইউনিট: {{unit}}), আপনার সার্ভিস চার্জ ({{amount}} টাকা) এখনো বকেয়া আছে। অনুগ্রহ করে দ্রুত পরিশোধ করুন। ধন্যবাদ।',
      tenantConfirmTemplate: `🏢 হলান টাওয়ার

প্রিয় বাসিন্দা,

ইউনিট: {unit}

গত {previous_month} মাসের সার্ভিস চার্জ সফলভাবে গ্রহণ করা হয়েছে।

পরিশোধিত পরিমাণ: ৳{amount}

আপনার সময়মতো পরিশোধ ও সহযোগিতার জন্য আন্তরিক ধন্যবাদ।

— হলান টাওয়ার ব্যবস্থাপনা`,
      tenantDueTemplate: `চলতি মাসের ইউটিলিটি চার্জ।

🏢 হলান টাওয়ার

প্রিয় বাসিন্দা,

ইউনিট: {unit}

{current_month} মাস শুরু হওয়ার সাথে সাথে
গত {previous_month} মাসের সার্ভিস চার্জ এখন পরিশোধযোগ্য হয়েছে।

পরিশোধযোগ্য পরিমাণ: ৳{due_amount}

অনুগ্রহ করে আগামী ৭ তারিখের মধ্যে পরিশোধ করার জন্য অনুরোধ করা হলো।

আপনার সহযোগিতার জন্য ধন্যবাদ।

— হলান টাওয়ার ব্যবস্থাপনা`,
      ownerConfirmTemplate: "Dear Owner, Payment received for Unit {unit}. Month: {month}. Amount: {amount}.",
      ownerDueTemplate: "Dear Owner, Payment DUE for Unit {unit}. Month: {month}. Amount: {amount}. Total Due: {due_amount}.",
      smsMessage: 'এসএমএস মেসেজ',
      and: 'এবং',
      use: 'ব্যবহার করুন',
      close: 'বন্ধ করুন',
      edit: 'এডিট',
      editAction: 'এডিট করুন',
      selectUnit: 'ইউনিট সিলেক্ট করুন',
      emergencyNote: 'জরুরী নোট',
      monthGrid: 'মাসের গ্রিড',
      paidCount: 'পরিশোধ করেছে',
      total: 'মোট',
      year2025: '২০২৫',
      year2026: '২০২৬',
      currencySymbol: '৳',
      saveError: 'সেভ করতে সমস্যা হয়েছে: ',
      unknownError: 'একটি ত্রুটি ঘটেছে: ',
    },
    waterBillView: {
      title: 'পানির বিল',
      subtitle: 'ওয়াসা বিল তথ্য',
      comingSoon: 'এই ফিচারটি খুব শীঘ্রই আসছে।',
      description: 'আমরা বর্তমানে পানির বিল সেকশনটি তৈরি করছি। এখানে আপনি আপনার মাসিক ওয়াসার বিল এবং পেমেন্টের তথ্য দেখতে পারবেন। ধৈর্য ধরার জন্য ধন্যবাদ।',
      back: 'ফিরে যান'
    },
    contactView: {
      title: 'যোগাযোগ',
      emergencyContact: 'জরুরী যোগাযোগ নম্বর',
      managementCommittee: 'ব্যবস্থাপনা কমিটি',
      securityGuard: 'নিরাপত্তা প্রহরী',
      caretaker: 'কেয়ারটেকার',
      liftOperator: 'লিফট অপারেটর',
      electrician: 'ইলেকট্রিশিয়ান',
      plumber: 'প্লাম্বার',
      call: 'কল করুন',
      whatsapp: 'হোয়াটসঅ্যাপ'
    },
    liftInstructionsView: {
      title: 'লিফট নির্দেশাবলি',
      subtitle: 'নিরাপদ ও সুন্দর অভিজ্ঞতার জন্য',
      emergencyContact: 'জরুরি প্রয়োজনে যোগাযোগ করুন',
      authority: 'হলান টাওয়ারের কর্তৃপক্ষ',
      thanks: 'ধন্যবাদান্তে,',
      instructions: [
        "হলান টাওয়ার লিফটে আপনাকে স্বাগতম।",
        "অনুগ্রহপূর্বক লাইনে দাঁড়ান এবং ধৈর্য ধরুন।",
        "উপরে বা নিচে নামার জন্য নির্ধারিত বাটন চাপুন।",
        "বাটন চাপার পর আলো জ্বলা পর্যন্ত অপেক্ষা করুন।",
        "লিফটের দরজা সম্পূর্ণ খোলার পর প্রবেশ করুন।",
        "আপনার কাঙ্ক্ষিত ফ্লোরের বাটন একবার চাপুন।",
        "ধারন ক্ষমতার অতিরিক্ত ওজন বহন থেকে বিরত থাকুন। (সর্বোচ্চ ৮ জন বা ৬৩০ কেজি)",
        "অতিরিক্ত ওজনের সংকেত বাজলে সর্বশেষ আরোহনকারী নেমে পড়ুন।",
        "লিফটের ভিতরে ধুমপান করা সম্পূর্ণ নিষিদ্ধ।",
        "শিশু ও বৃদ্ধদের একা একা লিফটে ভ্রমণ করতে নিরুৎসাহিত করা হচ্ছে।",
        "লিফটে সকল প্রকার ময়লা আবর্জনা ফেলা থেকে বিরত থাকুন।",
        "বিদ্যুৎ চলে গেলে আতঙ্কিত হবেন না, অটো রেস্কিউ ডিভাইস আপনাকে নিকটস্থ ফ্লোরে নিয়ে যাবে।",
        "যান্ত্রিক ত্রুটিতে লিফটের ভিতরের কলিং বেল চাপুন এবং কর্তৃপক্ষের সাহায্য নিন।",
        "লিফটের ভিতরে পর্যাপ্ত বায়ু চলাচল ও ইমারজেন্সি লাইটের ব্যবস্থা রয়েছে।"
      ]
    },
    policyView: {
      title: 'নীতিমালা অনুমোদন ও কার্যকর',
      subtitle: 'হলান টাওয়ার ব্যবস্থাপনা',
      intro: 'হলান টাওয়ার এর সকল ফ্ল্যাট মালিকদের সম্মতিক্রমে নিম্নলিখিত নীতিমালা অনুমোদন ও কার্যকর করা হলোঃ',
      thanks: 'ধন্যবাদ',
      footer: 'সকলের সহযোগিতায় আমাদের ভবনকে সুন্দর ও সুশৃঙ্খল রাখা সম্ভব।',
      policies: [
        "হলান টাওয়ার পরিচালনার নিমিত্তে নতুন করে একজন সেক্রেটারী, সভাপতি ও ক্যাশিয়ার নিয়োগ করা হবে। ক্যাশিয়ার নতুনভাবে সকল হিসাব সংরক্ষণ করবেন।",
        "সভাপতি, সেক্রেটারী, ক্যাশিয়ার এবং দুইজন নির্বাহী সদস্য নিয়ে ভোটের মাধ্যমে বিল্ডিং পরিচালনা কমিটি গঠন করতে হবে।",
        "হলান টাওয়ারে অবস্থানরত সদস্যদের সমন্বয়ে মিটিং অনুষ্ঠিত করে প্রয়োজন অনুযায়ী সেক্রেটারী ও অন্যান্য সদস্য নিয়োগ করা হবে।",
        "হলান টাওয়ারে বসবাসকারী মালিকদের মধ্য হতে প্রতি বছর সভাপতি ও সেক্রেটারী নির্বাচিত হবেন।",
        "হলান টাওয়ারের মালিকদের মধ্য থেকে ৩ সদস্য বিশিষ্ট একটি কার্যনির্বাহী কমিটি গঠন করা হবে। উক্ত কমিটি হলান টাওয়ারের নিয়ম-শৃঙ্খলা ও উন্নয়নমূলক কার্যক্রম সংক্রান্ত বিষয়াদি সভাপতি ও সেক্রেটারীর সাথে সমন্বয় করে পরিচালনা করবেন।",
        "আর্থিক বা গুরুত্বপূর্ণ কোনো সিদ্ধান্ত গ্রহণের ক্ষেত্রে গ্রুপ মিটিং আয়োজন করা হবে।",
        "হলান টাওয়ারের নিকটবর্তী IFIC ব্যাংকে একটি যৌথ ব্যাংক একাউন্ট খোলা হবে।",
        "প্রতিমাসের সার্ভিস চার্জ, ভাড়াটিয়ার গ্যারেজ ভাড়া এবং যে কোনো আয়ের উৎস থেকে প্রাপ্ত অর্থ ব্যাংক একাউন্টে জমা ও সংযুক্ত করতে হবে।",
        "পানি, গ্যাস ও বিদ্যুৎ বিলের ভাউচার ফাইল তৈরি করতে হবে। অন্যান্য আনুষঙ্গিক খরচের জন্য পৃথক ভাউচার ফাইল তৈরি করতে হবে।",
        "সভাপতির অনুমতি ব্যতীত কোনো প্রকার খরচ করা যাবে না।",
        "তিন মাস অন্তর অন্তর একটি অডিট টিম গঠন করে সকল সদস্যদের নিকট আয়-ব্যয়ের হিসাব প্রদান করতে হবে।",
        "ইউটিলিটি সার্ভিস চার্জ প্রতি মাসে ২০০০ টাকা নির্ধারণ করা হলো। খালি ইউনিটের জন্য প্রতি মাসে ৫০০ টাকা সার্ভিস চার্জ প্রযোজ্য হবে এবং তা সংশ্লিষ্ট ফ্ল্যাট মালিক বহন করবেন।",
        "ইউটিলিটি সার্ভিস চার্জ প্রতি মাসের ৫ তারিখের মধ্যে পরিশোধ করতে হবে।",
        "ভাড়াটিয়ার গাড়ি থাকলে নির্ধারিত হারে গ্যারেজ ভাড়া আদায় করতে হবে।",
        "২১ জন মালিকের ব্যক্তিগত প্রাইভেট গাড়ির গ্যারেজ ভাড়া ১০০০ টাকা নির্ধারণ করা হলো।",
        "২১ জন মালিকের ব্যক্তিগত বাইকের গ্যারেজ ভাড়া ৫০০ টাকা নির্ধারণ করা হলো।",
        "ভাড়াটিয়ার ব্যক্তিগত প্রাইভেট গাড়ির গ্যারেজ ভাড়া ২০০০ টাকা নির্ধারণ করা হলো (গ্যারেজ ফাঁকা সাপেক্ষে সুবিধা প্রদান করা হবে)।",
        "ভাড়াটিয়ার ব্যক্তিগত বাইকের গ্যারেজ ভাড়া ৫০০ টাকা নির্ধারণ করা হলো (গ্যারেজ ফাঁকা থাকা সাপেক্ষে সুবিধা প্রদান করা হবে)।",
        "ভাড়াটিয়ার বাসা ভাড়া ফরম (থানা কর্তৃক প্রদত্ত) পূরণ করে প্রত্যেক সদস্যের ১ কপি পিপি সাইজের ছবি, এনআইডি এর ফটোকপি এবং কর্মস্থলের ঠিকানা সেক্রেটারীর নিকট জমা দিতে হবে।",
        "ভাড়াটিয়াদের করণীয় বিষয়সমূহ সেক্রেটারী কর্তৃক লিখিতভাবে প্রদান করা হবে।",
        "আর্থিক বা গুরুত্বপূর্ণ কোনো সিদ্ধান্ত গ্রহণের ক্ষেত্রে গ্রুপ মিটিং আয়োজন করা হবে।",
        "কোনো ফ্ল্যাটের মালিক কোনো প্রকার সাবলেট ভাড়া প্রদান করতে পারবেন না।",
        "ভাড়াটিয়াদের পরিবারের সদস্য সংখ্যা ৫ জনের অধিক হতে পারবে না।",
        "কোনো ফ্ল্যাটের মালিক তার ফ্ল্যাট ভাড়া দেওয়ার পূর্বে ভাড়াটিয়ার এনআইডি ও কর্মস্থলের ঠিকানা সেক্রেটারীর নিকট জমা প্রদান নিশ্চিত করবেন।",
        "রাত ১১:৩০ ঘটিকার পর মেইন গেইট সম্পূর্ণ বন্ধ রাখা হবে।",
        "হলান টাওয়ারের মেইন গেইটের চাবি শুধুমাত্র ফ্ল্যাট মালিকদের প্রদান করা হবে। কোনো ভাড়াটিয়ার কাছে চাবি রাখা যাবে না।",
        "সর্বসময় গেইট লক থাকবে এবং কেয়ারটেকার পরিচয় নিশ্চিত না হওয়া পর্যন্ত কাউকে প্রবেশ করতে দেওয়া হবে না।",
        "কোনো ভাড়াটিয়া রাষ্ট্রবিরোধী কার্যকলাপ বা অসদাচরণে জড়িত থাকলে সভাপতি ও সেক্রেটারী তাকে বাসা ছেড়ে দেওয়ার নির্দেশ দিতে পারবেন। সে ক্ষেত্রে ফ্ল্যাট মালিকের কোনো আপত্তি গ্রহণযোগ্য হবে না।",
        "সভাপতি ও সেক্রেটারীর অনুমতি ব্যতীত বহিরাগতদের দ্বারা হল রুম ও ছাদ ব্যবহার সম্পূর্ণ নিষিদ্ধ।",
        "কেয়ারটেকারের পদ খালি রেখে ব্যক্তিগত কাজে কেয়ারটেকারকে ব্যবহার করা যাবে না।",
        "ছাদ সম্পূর্ণ খালি রাখা হবে এবং কোনো ধরনের গাছের টব ব্যবহার করা যাবে না।",
        "ছাদ শুধুমাত্র নির্ধারিত সময়ে খোলা থাকবে (বিকাল ৪:০০টা থেকে রাত ৮:০০টা পর্যন্ত)।"
      ]
    },
    emergency: {
      title: 'জরুরী যোগাযোগ',
      helplineTitle: 'জাতীয় হেল্পলাইন',
      helplineSubtitle: 'পুলিশ, ফায়ার সার্ভিস ও অ্যাম্বুলেন্স',
      helplineNumber: '৯৯৯',
      addDept: 'বিভাগ যোগ করুন',
      deptName: 'বিভাগের নাম',
      editNumber: 'নম্বর পরিবর্তন',
      addNumber: 'নম্বর যোগ করুন',
      hasWhatsApp: 'হোয়াটসঅ্যাপ আছে?',
      confirmDelete: 'আপনি কি নিশ্চিতভাবে এই নম্বরটি মুছে ফেলতে চান?',
      confirmDeleteDept: 'আপনি কি নিশ্চিতভাবে এই বিভাগটি মুছে ফেলতে চান? এর ভেতরের সকল নম্বর মুছে যাবে।',
      categories: {
        management: 'বিল্ডিং ম্যানেজমেন্ট',
        construction: 'নির্মাণ ও মেরামত',
        daily: 'দৈনিক সেবা',
        internet: 'ইন্টারনেট ও টিভি'
      },
      roles: {
        secretary: 'সেক্রেটারি',
        cashier: 'ক্যাশিয়ার',
        member: 'কার্যকরী সদস্য',
        security: 'নিরাপত্তা ও তত্ত্বাবধান',
        contractor: 'নির্মাণ ঠিকাদার',
        electrician: 'বিদ্যুৎ ঠিকাদার',
        plumber: 'পয়ঃনিষ্কাশন ঠিকাদার',
        plumbing: 'প্লাম্বিং সার্ভিস',
        cleaner: 'ময়লা ফেলার সার্ভিস',
        gas: 'গ্যাস সিলিন্ডার',
        ispHotline: 'ISP হটলাইন',
        ispSupport: 'ISP সাপোর্ট',
        ispAlt: 'ISP বিকল্প',
        dish: 'ডিস / কেবল টিভি',
        dishCollector: 'ডিস বিল কালেক্টর'
      }
    },
    emergencyNoticeDetailView: {
      title: 'জরুরী নোটিশ',
      publishedDate: 'প্রকাশের তারিখ',
      noNotice: 'কোনো নোটিশ পাওয়া যায়নি',
      backToHome: 'হোমে ফিরে যান',
      adminLogin: 'এডমিন লগইন',
      enterPin: 'পিন কোড দিন',
      login: 'লগইন করুন',
      logout: 'লগআউট',
      incorrectPin: 'ভুল পিন কোড!',
      addNotice: 'নতুন নোটিশ যোগ করুন',
      editNotice: 'নোটিশ এডিট',
      deleteNotice: 'নোটিশ ডিলিট',
      noticeName: 'নোটিশের নাম',
      date: 'তারিখ',
      pdfLink: 'ড্রাইভ লিংক (PDF)',
      description: 'পিডিএফ এর নিচের লেখা (ঐচ্ছিক)',
      publish: 'পাবলিশ করুন',
      publishing: 'পাবলিশ হচ্ছে...',
      pinnedNotice: 'পিন করা নোটিশ',
      allNotices: 'সকল নোটিশ',
      footerInfo: 'উপরোক্ত সকল নোটিশসমূহ হলান টাওয়ার কর্তৃপক্ষের নির্দেশক্রমে প্রকাশ করা হলো।',
      confirmDelete: 'আপনি কি নিশ্চিত যে এই নোটিশটি ডিলিট করতে চান? এটি আর ফিরে পাওয়া যাবে না।',
      cancel: 'বাতিল',
      delete: 'ডিলিট করুন',
      save: 'সেভ করুন',
      bold: 'বোল্ড লেখা',
      boldTooltip: 'বোল্ড করুন',
      placeholderTitle: 'উদা: পানির বিল সংক্রান্ত নোটিশ',
      placeholderDesc: 'পিডিএফ এর নিচে দেখাবে... (বোল্ড করতে লেখা সিলেক্ট করে B বাটনে ক্লিক করুন)',
      placeholderLink: 'https://drive.google.com/...',
      importantNotice: 'আপনার গুরুত্বপূর্ণ নোটিশ',
      requestFollow: 'সকলকে মেনে চলার জন্য অনুরোধ করা হচ্ছে',
      openInBrowser: 'ব্রাউজারে ওপেন করুন',
      noticeBoard: 'নোটিশবোর্ড',
      loading: 'লোড হচ্ছে...',
      newNoticeForm: 'নতুন নোটিশ ফরম',
      titlePlaceholder: 'টাইটেল',
      datePlaceholder: 'তারিখ (উদা: ১ জানুয়ারি)',
      pdfLinkPlaceholder: 'পিডিএফ লিংক',
      detailsText: 'বিস্তারিত লেখা',
      detailsPlaceholder: 'বিস্তারিত লিখুন',
      pinNotice: 'পিন করুন',
      unpinNotice: 'আনপিন করুন',
      edit: 'এডিট'
    },
    descoRulesView: {
      title: 'ডেসকো রিচার্জের নিয়ম',
      steps: 'রিচার্জ করার ধাপসমূহ',
      note: 'বিশেষ দ্রষ্টব্য'
    },
    downloadAppView: {
      title: 'অ্যাপ ডাউনলোড',
      description: 'হলান টাওয়ার অ্যাপটি ডাউনলোড করে আপনার স্মার্টফোনে ইন্সটল করুন।',
      downloadBtn: 'ডাউনলোড করুন',
      steps: 'ইন্সটল করার নিয়ম'
    },
    toLetView: {
      title: 'বাসাভাড়া / টু-লেট',
      availableFlats: 'উপলব্ধ ফ্ল্যাটসমূহ',
      flatDetails: 'ফ্ল্যাটের বিবরণ',
      rent: 'ভাড়া',
      contactForRent: 'ভাড়ার জন্য যোগাযোগ করুন',
      noFlats: 'বর্তমানে কোনো ফ্ল্যাট খালি নেই'
    },
    aiAssistant: {
      title: 'এআই অ্যাসিস্ট্যান্ট',
      greeting: 'হ্যালো! আমি আপনাকে কীভাবে সাহায্য করতে পারি?',
      placeholder: 'আপনার প্রশ্ন লিখুন...',
      error: 'দুঃখিত, আমি এখন উত্তর দিতে পারছি না। আবার চেষ্টা করুন।'
    },
    settingsView: {
      title: 'সেটিংস',
      language: 'ভাষা (Language)',
      darkMode: 'ডার্ক মোড',
      on: 'চালু',
      off: 'বন্ধ',
      adminPanel: 'অ্যাডমিন প্যানেল'
    }
  },
  en: {
    appName: 'Holan Tower',
    common: {
      serviceCenter: 'Service Center',
      allServices: 'All Services',
      viewAll: 'View All',
      todayDate: 'Today\'s Date',
      seconds: 'Seconds',
      maintenanceDesk: 'Maintenance Desk',
      settings: 'Settings',
      back: 'Back',
      save: 'Save',
      cancel: 'Cancel',
      confirm: 'Confirm',
      loading: 'Loading...',
      error: 'Error',
      success: 'Success',
      delete: 'Delete',
      edit: 'Edit',
      add: 'Add',
      search: 'Search...',
      noData: 'No data found',
      viewDetails: 'View Details',
      hideDetails: 'Hide Details',
      showDetails: 'Show Details',
      yes: 'Yes',
      no: 'No',
      ok: 'OK',
      retry: 'Retry',
      saveError: 'Problem saving: ',
      unknownError: 'An error occurred: ',
    },
    hollanTowerResident: 'Holan Tower Resident',
    serviceCharge: 'Service Charge',
    demo: 'Demo',
    adminDashboard: 'Admin Dashboard',
    editInfo: 'Click any unit to change payment status.',
    allUnitsCalc: 'All Units Calculation',
    financialYear: 'Financial Year',
    total: 'Total',
    status: 'Status',
    unit: 'Unit',
    totalCollected: 'Total Collected',
    totalDue: 'Total Due',
    searchUnit: 'Search Unit (e.g., 2A)',
    details: 'Click to view details',
    all: 'All',
    flatType: 'Flat Type',
    paid: 'Paid',
    due: 'Due',
    upcoming: 'Upcoming',
    adminLogin: 'Admin Login',
    loginPrompt: 'Enter PIN to edit data',
    loginBtn: 'Login',
    totalAmount: 'Total Amount',
    occupancy: 'Occupancy',
    occupied: 'Occupied',
    vacant: 'Vacant',
    monthDate: 'Month & Date',
    amount: 'Amount',
    saveFail: 'Failed to save',
    statusChangeFail: 'Failed to change status',
    month: 'Month',
    paymentStatus: 'Payment Status',
    notice: 'Notice',
    exitTitle: 'Exit App',
    exitMessage: 'Are you sure you want to exit the app?',
    exitConfirm: 'Yes, Exit',
    exitCancel: 'No',
    mobile: 'Mobile',
    note: 'Note',
    date: 'Date',
    year: 'Year',
    balance: 'Balance',
    income: 'Income',
    expense: 'Expense',
    action: 'Action',
    admin: 'Admin',
    user: 'User',
    password: 'Password',
    incorrectPassword: 'Incorrect Password',
    pin: 'PIN',
    incorrectPin: 'Incorrect PIN!',
    securityPin: 'Security PIN',
    unlockEdit: 'Unlock Edit Mode',
    months: [
      'January', 'February', 'March', 'April', 'May', 'June',
      'July', 'August', 'September', 'October', 'November', 'December'
    ],
    menuItems: {
      service: { label: 'Service Charge', desc: 'Monthly Bill & Payment' },
      desco: { label: 'Desco Recharge', desc: 'Prepaid Meter Info' },
      recharge_rules: { label: 'Recharge Rules', desc: 'Easy Recharge Guide' },
      accounts: { label: 'Accounts Center', desc: 'Building Income-Expense' },
      tolet: { label: 'To-Let', desc: 'Flat Available' },
      emergency: { label: 'Emergency Numbers', desc: 'Police, Fire, Ambulance' },
      emergency_notice: { label: 'Emergency Notice', desc: 'Important Announcement' },
      water: { label: 'Water Bill', desc: 'Wasa Bill Info' },
      map: { label: 'Map & Routes', desc: 'Location & Directions' },
      prayer: { label: 'Prayer Time', desc: 'Today\'s Prayer Schedule' },
      policy: { label: 'Policy Approval', desc: 'Rules & Guidelines' },
      lift: { label: 'Lift Instructions', desc: 'Lift Usage Rules' },
      download: { label: 'Download App', desc: 'Download the App' },
      contact: { label: 'Contact', desc: 'Emergency Contact Numbers' }
    },
    bottomNav: {
      service: 'Service Charge',
      desco: 'Desco',
      home: 'Home',
      contact: 'Contact',
      menu: 'Menu'
    },
    greetings: {
      morning: 'Good Morning',
      noon: 'Good Noon',
      afternoon: 'Good Afternoon',
      evening: 'Good Evening',
      night: 'Good Night'
    },
    location: 'Holan, Dakshinkhan',
    designBy: 'Design By A.H.M RIFAT HASAN',
    notices: [
      "Pay monthly service charge by the 7th of every month",
      "Service charge money is spent on building maintenance",
      "Prevent water and electricity wastage",
      "Turn off gas stove and electric lines before going out",
      "Know the location of fire extinguishers",
      "Dispose of garbage in designated areas",
      "Ensure building security",
      "Be careful when using the lift"
    ],
    menuNotice: "Welcome to Holan Tower. Here you will quickly find all the important information and daily services of our building. Easily find emergency notices, utility and service charges, Desco recharge, contact and emergency helplines, maps and route directions, prepaid meter numbers, lift usage rules, gallery, and flat rent information all in one place. This is a fast, easy, and reliable digital service center for the residents of Holan Tower.",
    descoNotice: "An account number is required to recharge Desco prepaid meters. All unit account numbers mentioned below have been updated. Recharge carefully so that one meter's recharge does not go to another meter.",
    serviceChargeNotice: "Please pay next month's service charge by the 7th of every month. Failure to pay within the specified time may disrupt building maintenance, security, cleanliness, and other service activities. Let's keep our building clean, safe, and orderly with everyone's cooperation. -- Thank you, Management Committee",
    emergencyNotice: "Dear flat owners and residents, if any building-related issues arise such as lift, electricity, water, gas, security, or other emergency matters, please contact the emergency contact numbers provided on the notice board/app quickly. Quick contact will make it easier and faster to solve the problem. Let's keep our building safe and orderly with everyone's cooperation.",
    accounts: {
      title: 'Transparent Accounts',
      subtitle: 'Annual Financial Statement',
      currentBalance: 'Current Balance',
      totalIncome: 'Total Income',
      totalExpense: 'Total Expense',
      netSurplus: 'Net Surplus',
      incomeDetails: 'Income Statement',
      expenseDetails: 'Expense Statement',
      surplusFromLastMonth: 'Surplus from Last Month',
      fixedExpenses: {
        electricity: 'Electricity Bill',
        water: 'Water Bill',
        garbage: 'Garbage Bill',
        caretaker: 'Caretaker Salary',
        nightGuard: 'Night Guard Bill',
      },
      otherIncome: 'Other Income',
      otherExpense: 'Other Expense',
      specialNote: 'Special Note / Comment',
      upcoming: 'Upcoming',
    },
    descoView: {
      title: 'DESCO Smart Meter',
      accountNo: 'Account No',
      meterNo: 'Meter No',
      checkBalance: 'Check Balance',
      recharge: 'Recharge',
      quickRecharge: 'Quick Recharge',
      paymentGuide: 'Payment Guide',
      confirmRecharge: 'Confirm Recharge',
      loadingMeter: 'Loading meter info',
      meterNotFound: 'Meter info not found',
      selectFlat: 'Select your flat number',
      noFlatSelected: 'No flat selected',
      searchPlaceholder: 'Search (e.g. 2A or name)...',
      noResult: 'No results found',
      flatNumber: 'Your flat number',
      ownerName: 'Owner name',
      accountNumber: 'DESCO account number',
      confirmTitle: 'Confirm Action',
      confirmDesc: 'Click the button below to copy the account number',
      subtitle: 'Prepaid Meter Info',
      infoBox: 'Meter Info',
      rulesBox: 'Recharge Rules',
      allFloors: 'All Floors',
      mainMeter: 'Main Meter',
      notice: 'Note:',
      account: 'Account',
      tapToCopy: 'Tap to copy',
      flat: 'Flat',
      owner: 'Owner',
      paymentNote: 'Save the transaction ID after payment.',
      payNow: 'Pay Now',
      copySuccess: 'Account number copied!',
      copyFail: 'Copy failed',
      disclaimer: 'Information is for your assistance only.',
      warning: 'Warning: Authority will not be responsible for recharge to wrong account.',
      popupTitle: 'Quick Recharge Popup',
      popupText: 'Do you want to recharge this account?',
      popupNote: 'Warning: Verify account number before recharging.',
      popupDetails: 'Detailed Info',
      rechargeNow: 'Recharge Now',
      mobileBanking: 'Mobile Banking',
      floor: 'Floor',
    },
    emergencyView: {
      title: 'Emergency Services & Contractors',
      newDepartment: 'New Department',
      addNumber: 'Add New Number',
      editNumber: 'Edit Number',
      name: 'Name',
      role: 'Role',
      mobileNumber: 'Mobile Number',
      hasWhatsapp: 'Has WhatsApp',
      departmentName: 'Department Name',
      createDepartment: 'Create',
      call: 'Call',
      copied: 'Copied',
      confirmDeleteNumber: 'Are you sure you want to delete this number?',
      confirmDeleteDept: 'Are you sure you want to delete this entire department? All numbers within it will be deleted.',
    },
    serviceChargeView: {
      monthlyServiceCharge: 'Monthly Service Charge',
      dashboard: 'Service Charge Dashboard',
      allUnitsList: 'All Units List',
      paymentHistory: 'Payment History',
      dueList: 'Due List',
      parkingCharge: 'Parking Charge',
      adminPanel: 'Admin Panel',
      dataEntry: 'Data Entry',
      twelveMonthsInfo: '12 Months Info',
      unitAndDate: 'Unit & Date',
      partial: 'Partial',
      paidStatus: 'Paid',
      dueStatus: 'Due',
      remaining: 'Remaining',
      grandTotal: 'Grand Total',
      yearlySummary: 'Yearly Summary',
      yearlyCalculation: 'Calculation of',
      totalCollectedYear: 'Total Collected (Year)',
      totalDueYear: 'Total Due (Year)',
      highestDueMonth: 'Highest Due Month',
      wasDueThisMonth: 'Was due this month',
      totalBillable: 'Total Billable (Year)',
      paymentUpdate: 'Payment Update',
      occupancyType: 'Occupancy Type (For this month)',
      parkingType: 'Parking Type',
      motorcycle: 'Motorcycle',
      car: 'Car',
      ownershipType: 'Ownership Type',
      flatOwner: 'Flat Owner',
      tenant: 'Tenant',
      external: 'External',
      paymentDate: 'Payment Date',
      on: 'On',
      off: 'Off',
      updateBtn: 'Update',
      agingReport: 'Aging Report (Due)',
      oneMonthDue: '1 Month Due',
      twoMonthsDue: '2 Months Due',
      threePlusMonthsDue: '3+ Months Due',
      totalAccumulatedDue: 'Total Accumulated Due',
      units: 'Units',
      monthlyCharge: 'Monthly Charge',
      lastPayment: 'Last Payment',
      paymentMethod: 'Payment Method',
      allPaid: 'All Paid',
      totalDue: 'Total Due',
      infoOfTwelveMonths: '12 Months Info of',
      adminDashboard: 'Admin Dashboard',
      editInfo: 'Edit Information',
      whatsappMessage: 'WhatsApp Message',
      amount: 'Amount',
      noDateOrAmountNeeded: 'No date or amount needed',
      totalAmount: 'Total Amount',
      selectParkingUnitsDescription: 'Select the units that have parking',
      apiKeyPlaceholder: 'Enter your API Key',
      senderIdPlaceholder: 'Enter your Sender ID',
      paymentRequestTemplate: 'Payment Request',
      paymentRequestTemplateText: 'Dear resident (Unit: {{unit}}), please pay the service charge ({{amount}} Taka) for the current month. Thank you.',
      sendToAllUnits: 'Send to All Units',
      paymentReceivedTemplate: 'Payment Received',
      paymentReceivedTemplateText: 'Dear resident (Unit: {{unit}}), your service charge ({{amount}} Taka) has been successfully received. Thank you.',
      forIndividualUnits: 'For Individual Units',
      dueReminderTemplate: 'Due Reminder',
      dueReminderTemplateText: 'Dear resident (Unit: {{unit}}), your service charge ({{amount}} Taka) is still due. Please pay as soon as possible. Thank you.',
      tenantConfirmTemplate: `🏢 Hollan Tower

Dear Resident,

Unit: {unit}

The service charge for the last {previous_month} month has been successfully received.

Paid Amount: ৳{amount}

Thank you sincerely for your timely payment and cooperation.

— Hollan Tower Management`,
      tenantDueTemplate: `Utility charge for the current month.

🏢 Hollan Tower

Dear Resident,

Unit: {unit}

As the {current_month} month begins,
the service charge for the last {previous_month} month is now payable.

Payable Amount: ৳{due_amount}

You are requested to pay by the 7th of the upcoming month.

Thank you for your cooperation.

— Hollan Tower Management`,
      ownerConfirmTemplate: "Dear Owner, Payment received for Unit {unit}. Month: {month}. Amount: {amount}.",
      ownerDueTemplate: "Dear Owner, Payment DUE for Unit {unit}. Month: {month}. Amount: {amount}. Total Due: {due_amount}.",
      and: 'and',
      use: 'use',
      occupied: 'Occupied',
      vacant: 'Vacant',
      billNotGenerated: 'This month\'s bill is not generated yet',
      parkingChargeWithService: 'Parking Charge with Service Charge',
      viewTogether: 'View Together',
      onlyParkingCharge: 'Only Parking Charge',
      viewSeparately: 'View Separately',
      summaryReport: 'Summary Report',
      year: 'Year',
      flatNumber: 'Flat Number',
      unknown: 'Unknown',
      totalDueAmount: 'Total Due',
      unitDetailsInstruction: '. Click on a unit above to see its details. All unit details are provided.',
      parkingChargePdf: 'Download Parking Charge PDF',
      serviceChargePdf: 'Download Service Charge PDF',
      reportOfUnit: 'Report of Unit {{unit}} for {{year}}',
      emergencyNotePlaceholder: 'Enter emergency note here...',
      clickToAddNote: 'Click here to add note...',
      noNote: 'No note',
      detailedYearlyAccount: 'View detailed yearly account for this unit',
      paidList: 'Paid List',
      unitCount: '{{unit}} Count',
      remainingCount: 'Remaining',
      monthStatPaid: 'Out of {{total}} units, {{paid}} have paid this month.',
      monthStatDue: 'And out of {{total}} units, {{due}} are remaining.',
      noUnitFound: 'No unit found',
      upcoming: 'Upcoming',
      clickMonthForPopup: 'Clicking on a month will open a popup window for data entry',
      status: 'Status',
      unitLabel: 'Unit:',
      monthLabel: 'Month:',
      yearLabel: 'Year',
      calculationOf: 'Calculation of',
      count: 'Count',
      provideApiSenderMessage: 'Please provide API Key, Sender ID and Message.',
      selectAtLeastOneUnit: 'Please select at least one unit.',
      confirmSendSms: 'Are you sure you want to send SMS to {{count}} units?',
      receivedKeyword: 'received',
      acceptedKeyword: 'accepted',
      successfullyKeyword: 'successfully',
      smsSendingCompleted: 'SMS sending completed!\nSuccess: {{success}}\nFailed: {{fail}}',
      problemSendingSms: 'Problem sending SMS.',
      aiAssistant: 'AI Assistant',
      sendNotification: 'Send Notification',
      sendSms: 'Send SMS',
      sendSmsToAll: 'Send SMS to all units',
      manageParkingUnits: 'Manage Parking Units',
      addCarOrParking: 'Add Car or Parking',
      refreshData: 'Refresh Data',
      writeMessageHere: 'Write your message here...',
      selected: 'selected',
      deselectAll: 'Deselect All',
      selectAll: 'Select All',
      sent: 'Sent',
      sending: 'Sending...',
      currentMonthMessage: 'Current Month Message',
      dueMonthMessageOwner: 'Due Month Message (Owner)',
      dueSummary: 'Due Summary',
      years2025And2026: '2025 and 2026',
      totalDue2025: '2025 Total Due',
      totalDue2026: '2026 Total Due',
      grandTotalDue: 'Grand Total Due',
      unitWiseDueList: 'Unit-wise Due List',
      monthlySummary: 'Monthly Summary',
      viewDetailedYearlyAccount: 'View detailed account of the whole year',
      dueAccount2025And2026: 'Due account of 2025 and 2026',
      unitWiseSummary: 'Unit-wise Summary',
      viewYearlyAccount: 'View account of the whole year',
      viewDetails: 'View Details',
      backToServiceCharge: 'Back to Service Charge',
      currentlyViewingParkingCharge: 'Currently viewing parking charge',
      viewMonthlyDetailedAccount: 'View detailed account of each month',
      parkingUnits: 'Parking Units',
      selectParkingUnits: 'Select Parking Units',
      buildingUnits: 'Building Units',
      externalParking: 'External Parking',
      ownerName: 'Owner Name',
      add: 'Add',
      cancel: 'Cancel',
      save: 'Save',
      saving: 'Saving...',
      smsSender: 'SMS Sender',
      viaBulkSms: 'via BulkSMSBD API',
      apiKey: 'API Key',
      senderId: 'Sender ID',
      selectTarget: 'Select Target',
      selectMonth: 'Select Month',
      selectTemplate: 'Select Template',
      paymentRequest: 'Payment Request',
      paymentReceived: 'Payment Received',
      dueReminder: 'Due Reminder',
      smsMessage: 'SMS Message',
      clearAll: 'Clear All',
      noNumber: 'No Number',
      whatsappTitle: 'WhatsApp Message',
      sentCount: 'Sent Count',
      saveToSupabase: 'Save to Supabase',
      savedSuccessfully: 'Saved successfully!',
      savedLocally: 'Saved locally!',
      back: 'Back',
      whatsapp: 'WhatsApp',
      sms: 'SMS',
      pdf: 'PDF',
      download: 'Download',
      print: 'Print',
      share: 'Share',
      copy: 'Copy',
      link: 'Link',
      view: 'View',
      goBack: 'Go Back',
      home: 'Home',
      profile: 'Profile',
      notifications: 'Notifications',
      messages: 'Messages',
      contacts: 'Contacts',
      about: 'About',
      help: 'Help',
      faq: 'FAQ',
      terms: 'Terms & Conditions',
      privacy: 'Privacy Policy',
      contactUs: 'Contact Us',
      feedback: 'Feedback',
      rateUs: 'Rate Us',
      version: 'Version',
      developedBy: 'Developed by',
      allRightsReserved: 'All rights reserved',
      close: 'Close',
      edit: 'Edit',
      editAction: 'Edit',
      selectUnit: 'Select Unit',
      emergencyNote: 'Emergency Note',
      monthGrid: 'Month Grid',
      paidCount: 'Paid',
      total: 'Total',
      year2025: '2025',
      year2026: '2026',
      currencySymbol: '৳',
      saveError: 'Problem saving: ',
      unknownError: 'An error occurred: ',
    },
    waterBillView: {
      title: 'Water Bill',
      subtitle: 'WASA Bill Info',
      comingSoon: 'This feature is coming soon.',
      description: 'We are currently building the water bill section. Here you will be able to see your monthly WASA bill and payment information. Thank you for your patience.',
      back: 'Go Back'
    },
    contactView: {
      title: 'Contact',
      emergencyContact: 'Emergency Contact Numbers',
      managementCommittee: 'Management Committee',
      securityGuard: 'Security Guard',
      caretaker: 'Caretaker',
      liftOperator: 'Lift Operator',
      electrician: 'Electrician',
      plumber: 'Plumber',
      call: 'Call',
      whatsapp: 'WhatsApp'
    },
    liftInstructionsView: {
      title: 'Lift Instructions',
      subtitle: 'For a safe and pleasant experience',
      emergencyContact: 'Contact for emergency',
      authority: 'Hollan Tower Authority',
      thanks: 'Thank you,',
      instructions: [
        "Welcome to Hollan Tower Lift.",
        "Please stand in line and be patient.",
        "Press the designated button to go up or down.",
        "Wait until the light turns on after pressing the button.",
        "Enter after the lift door is fully open.",
        "Press the button for your desired floor once.",
        "Refrain from carrying weight beyond capacity. (Max 8 persons or 630 kg)",
        "If the overload signal sounds, the last person to enter should step out.",
        "Smoking inside the lift is strictly prohibited.",
        "Children and the elderly are discouraged from traveling in the lift alone.",
        "Refrain from throwing all kinds of garbage in the lift.",
        "Don't panic if the power goes out, the Auto Rescue Device will take you to the nearest floor.",
        "In case of mechanical failure, press the calling bell inside the lift and seek help from the authorities.",
        "There is adequate ventilation and emergency light inside the lift."
      ]
    },
    policyView: {
      title: 'Policy Approval & Implementation',
      subtitle: 'Hollan Tower Management',
      intro: 'With the consent of all flat owners of Hollan Tower, the following policies are approved and implemented:',
      thanks: 'Thank You',
      footer: 'With everyone\'s cooperation, it is possible to keep our building beautiful and orderly.',
      policies: [
        "A new Secretary, President, and Cashier will be appointed for the management of Hollan Tower. The Cashier will maintain all accounts anew.",
        "A building management committee must be formed through voting with the President, Secretary, Cashier, and two executive members.",
        "Meetings will be held with members residing in Hollan Tower to appoint a Secretary and other members as needed.",
        "The President and Secretary will be elected every year from among the owners residing in Hollan Tower.",
        "An executive committee consisting of 3 members will be formed from among the owners of Hollan Tower. The committee will manage matters related to the rules, discipline, and developmental activities of Hollan Tower in coordination with the President and Secretary.",
        "Group meetings will be organized for any financial or important decisions.",
        "A joint bank account will be opened at the nearby IFIC Bank of Hollan Tower.",
        "Money received from monthly service charges, tenant's garage rent, and any source of income must be deposited and linked to the bank account.",
        "Voucher files for water, gas, and electricity bills must be created. Separate voucher files must be created for other incidental expenses.",
        "No expenses can be made without the permission of the President.",
        "An audit team should be formed every three months to provide income and expenditure accounts to all members.",
        "Utility service charge is fixed at 2000 taka per month. A service charge of 500 taka per month will be applicable for empty units and will be borne by the respective flat owner.",
        "Utility service charges must be paid by the 5th of every month.",
        "If the tenant has a car, garage rent must be collected at the fixed rate.",
        "Garage rent for personal private cars of 21 owners is fixed at 1000 taka.",
        "Garage rent for personal bikes of 21 owners is fixed at 500 taka.",
        "Garage rent for the tenant's personal private car is fixed at 2000 taka (facilities will be provided subject to garage availability).",
        "Garage rent for the tenant's personal bike is fixed at 500 taka (facilities will be provided subject to garage availability).",
        "The tenant's house rent form (provided by the police station) must be filled out and 1 copy of PP size photograph of each member, photocopy of NID, and workplace address must be submitted to the Secretary.",
        "The duties of the tenants will be provided in writing by the Secretary.",
        "Group meetings will be organized for any financial or important decisions.",
        "No flat owner can provide any kind of sublet rent.",
        "The number of family members of the tenant cannot exceed 5.",
        "Before renting out a flat, the owner of the flat will ensure that the tenant's NID and workplace address are submitted to the Secretary.",
        "The main gate will be completely closed after 11:30 PM.",
        "The key to the main gate of Hollan Tower will be provided only to the flat owners. No tenant can keep the key.",
        "The gate will be locked at all times and no one will be allowed to enter until the caretaker confirms their identity.",
        "If any tenant is involved in anti-state activities or misconduct, the President and Secretary can order them to leave the house. In that case, no objection from the flat owner will be acceptable.",
        "Use of the hall room and roof by outsiders without the permission of the President and Secretary is strictly prohibited.",
        "The caretaker cannot be used for personal work while leaving the caretaker's post vacant.",
        "The roof will be kept completely empty and no kind of flower pots can be used.",
        "The roof will be open only at scheduled times (from 4:00 PM to 8:00 PM)."
      ]
    },
    emergency: {
      title: 'Emergency Contacts',
      helplineTitle: 'National Helpline',
      helplineSubtitle: 'Police, Fire Service & Ambulance',
      helplineNumber: '999',
      addDept: 'Add Department',
      deptName: 'Department Name',
      editNumber: 'Edit Number',
      addNumber: 'Add Number',
      hasWhatsApp: 'Has WhatsApp?',
      confirmDelete: 'Are you sure you want to delete this number?',
      confirmDeleteDept: 'Are you sure you want to delete this department? All numbers inside will be deleted.',
      categories: {
        management: 'Building Management',
        construction: 'Construction & Repair',
        daily: 'Daily Services',
        internet: 'Internet & TV'
      },
      roles: {
        secretary: 'Secretary',
        cashier: 'Cashier',
        member: 'Executive Member',
        security: 'Security & Supervision',
        contractor: 'Construction Contractor',
        electrician: 'Electrical Contractor',
        plumber: 'Sanitary Contractor',
        plumbing: 'Plumbing Service',
        cleaner: 'Waste Disposal Service',
        gas: 'Gas Cylinder',
        ispHotline: 'ISP Hotline',
        ispSupport: 'ISP Support',
        ispAlt: 'ISP Alternative',
        dish: 'Dish / Cable TV',
        dishCollector: 'Dish Bill Collector'
      }
    },
    emergencyNoticeDetailView: {
      title: 'Emergency Notice',
      publishedDate: 'Published Date',
      noNotice: 'No notice found',
      backToHome: 'Back to Home',
      adminLogin: 'Admin Login',
      enterPin: 'Enter PIN Code',
      login: 'Login',
      logout: 'Logout',
      incorrectPin: 'Incorrect PIN!',
      addNotice: 'Add New Notice',
      editNotice: 'Edit Notice',
      deleteNotice: 'Delete Notice',
      noticeName: 'Notice Name',
      date: 'Date',
      pdfLink: 'Drive Link (PDF)',
      description: 'Text below PDF (Optional)',
      publish: 'Publish',
      publishing: 'Publishing...',
      pinnedNotice: 'Pinned Notice',
      allNotices: 'All Notices',
      footerInfo: 'All the above notices are published by the order of Hollan Tower Authority.',
      confirmDelete: 'Are you sure you want to delete this notice? It cannot be recovered.',
      cancel: 'Cancel',
      delete: 'Delete',
      save: 'Save',
      bold: 'Bold Text',
      boldTooltip: 'Make Bold',
      placeholderTitle: 'e.g., Water Bill Notice',
      placeholderDesc: 'Will show below PDF... (Select text and click B to bold)',
      placeholderLink: 'https://drive.google.com/...',
      importantNotice: 'Your Important Notice',
      requestFollow: 'Everyone is requested to follow',
      openInBrowser: 'Open in Browser',
      noticeBoard: 'Notice Board',
      loading: 'Loading...',
      newNoticeForm: 'New Notice Form',
      titlePlaceholder: 'Title',
      datePlaceholder: 'Date (e.g. 1 January)',
      pdfLinkPlaceholder: 'PDF Link',
      detailsText: 'Details Text',
      detailsPlaceholder: 'Write details',
      pinNotice: 'Pin',
      unpinNotice: 'Unpin',
      edit: 'Edit'
    },
    descoRulesView: {
      title: 'Desco Recharge Rules',
      steps: 'Recharge Steps',
      note: 'Special Note'
    },
    downloadAppView: {
      title: 'Download App',
      description: 'Download the Hollan Tower app and install it on your smartphone.',
      downloadBtn: 'Download Now',
      steps: 'Installation Steps'
    },
    toLetView: {
      title: 'To-Let / Flat Rent',
      availableFlats: 'Available Flats',
      flatDetails: 'Flat Details',
      rent: 'Rent',
      contactForRent: 'Contact for Rent',
      noFlats: 'No flats currently available'
    },
    aiAssistant: {
      title: 'AI Assistant',
      greeting: 'Hello! How can I help you?',
      placeholder: 'Type your question...',
      error: 'Sorry, I cannot answer right now. Please try again.'
    },
    settingsView: {
      title: 'Settings',
      language: 'Language',
      darkMode: 'Dark Mode',
      on: 'On',
      off: 'Off',
      adminPanel: 'Admin Panel'
    }
  }
};

export const VIEW_TO_PATH: Record<string, string> = {
  HOME: '/',
  MENU: '/menu.html',
  DESCO: '/desco.html',
  DESCO_INFO: '/desco-info.html',
  DESCO_RULES: '/desco-rules.html',
  ACCOUNTS: '/accounts.html',
  SERVICE_CHARGE: '/service-charge.html',
  EMERGENCY: '/emergency.html',
  TO_LET: '/to-let.html',
  WATER_BILL: '/water-bill.html',
  LIFT_INSTRUCTIONS: '/lift-instructions.html',
  MAINTENANCE: '/maintenance.html',
  SETTINGS: '/settings.html',
  PRAYER_TIME: '/prayer-time.html',
  RECHARGE_RULES: '/recharge-rules.html',
  POLICY: '/policy.html',
  CONTACT: '/contact.html',
  DOWNLOAD_APP: '/download-app.html',
  EMERGENCY_NOTICE_DETAIL: '/emergency-notice.html',
  MAP_ROUTES: '/map-routes.html',
  AI_ASSISTANT: '/assistant.html'
};

export const BOTTOM_NAV_ITEMS = [
  { id: 'service', label: 'সার্ভিস চার্জ', icon: CreditCard, view: 'SERVICE_CHARGE' },
  { id: 'desco', label: 'ডেসকো', icon: Zap, view: 'DESCO' },
  { id: 'home', label: 'হোম', icon: Home, view: 'HOME' },
  { id: 'contact', label: 'যোগাযোগ', icon: Phone, view: 'CONTACT' },
  { id: 'menu', label: 'মেনু', icon: MenuIcon, view: 'MENU' },
] as const;